batch_size: 32
block_length: 40
clip_length: 10000
dataset: TUT
dataset_location: /nas/student/WilliSchiebelbein/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 20
epochs: 100
fold: 1
learning_rate: 0.0005
model:
  name: AdvancedCRNN
n_fft: 2048
n_mels: 40
normalize: true
optimizer: Adam
overlap: 0.5
seed: 42
use_specaug: false
use_weights: true
