batch_size: 32
block_length: 40
clip_length: 10000
dataset: TUT
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 20
epochs: 100
fold: 2
learning_rate: 0.0005
model:
  name: Baseline
n_fft: 2048
n_mels: 128
normalize: false
optimizer: Adam
overlap: 0.5
seed: 42
use_specaug: false
use_weights: true
