batch_size: 24
block_length: 40
clip_length: 10000
dataset: desed_2022
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 40
epochs: 400
fold: 1
learning_rate: 0.0001
model:
  name: Baseline
n_fft: 2048
n_mels: 128
normalize: false
optimizer: Adam
overlap: 0.5
save_folder: /dcase_baseline
seed: 42
use_ast_features: false
use_specaug: true
use_weights: false
