batch_size: 32
block_length: 40
clip_length: 10000
dataset: BirdSED
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.5
early_stopping: 50
epochs: 400
fold: 3
learning_rate: 0.0005
model:
  name: Baseline
n_fft: 2048
n_mels: 128
normalize: false
optimizer: Adam
overlap: 0.5
seed: 42
use_specaug: true
use_weights: false
