batch_size: 16
block_length: 40
clip_length: 10000
dataset_location: /nas/student/WilliSchiebelbein/
decision_threshold: 0.5
dropout: 0.5
early_stopping: 40
epochs: 400
learning_rate: 0.0005
n_fft: 2048
n_mels: 64
normalize: false
optimizer: Adam
overlap: 0.5
seed: 42
use_specaug: true
use_weights: false
