batch_size: 8
block_length: 40
clip_length: 10000
dataset: TUT
dataset_location: /nas/student/WilliSchiebelbein/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 40
epochs: 400
fold: 1
learning_rate: 0.0001
model:
  name: ShakeRCNN
n_fft: 2048
n_mels: 128
normalize: false
optimizer: Adam
overlap: 0.5
save_folder: /rcnn_1
seed: 42
use_ast_features: true
use_specaug: true
use_weights: true
