batch_size: 32
block_length: 40
clip_length: 10000
dataset: desed_2022
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 20
epochs: 200
fold: 3
learning_rate: 0.0005
model:
  name: Advanced
n_fft: 2048
n_mels: 40
normalize: false
optimizer: Adam
overlap: 0.5
seed: 42
use_specaug: true
use_weights: false
