batch_size: 12
block_length: 40
clip_length: 10000
dataset: desed_2022
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.2
ema_decay: 0.999
iterations: 20000
learning_rate: 0.0005
model:
  name: AdvancedRCNN
n_fft: 2048
n_mels: 40
normalize: false
optimizer: Adam
overlap: 0.5
seed: 42
unlabelled_threshold: 0.4
use_hard_labels: false
use_specaug: false
val_step: 5
