batch_size: 16
block_length: 40
clip_length: 10000
dataset: BirdSED
dataset_location: dataset/
decision_threshold: 0.5
dropout: 0.2
early_stopping: 50
epochs: 400
fold: 1
learning_rate: 0.0005
model:
  name: ASTRCNN
n_fft: 2048
n_mels: 128
normalize: false
optimizer: Adam
overlap: 0.5
save_folder: ''
seed: 42
use_weights: false
